import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainNav}>
        <ul>
          <Link href="/"><li>Home</li></Link>
          
          <Link href="/about"><li>About</li></Link>
          <Link href="/blogs"><li>Blogs</li></Link>
          <Link href="/contact"><li>Contact</li></Link>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <h2>Popular Blogs</h2>
        <div className={styles.grid}>
          <div>
            <h3>How to learn Next.JS</h3>
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi,
              incidunt!
            </p>
          </div>
          <div>
            <h3>How to learn Next.JS</h3>
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi,
              incidunt!
            </p>
          </div>
          <div>
            <h3>How to learn Next.JS</h3>
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi,
              incidunt!
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
